# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  displayName: 'init'
  inputs:
    command: 'init'
    backendType: 'azurerm'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'sxp-terraform-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'sxpstorageaccount1'
    backendAzureRmContainerName: 'sxpstoragecontainer'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  displayName: 'plan'
  inputs:
    command: 'plan'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  displayName: 'apply'
  inputs:
    command: 'apply'
    allowTelemetryCollection: true