# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azure-service-connection'
    backendAzureRmResourceGroupName: 'sxp-terraform-rg'
    backendAzureRmStorageAccountName: 'sxpstorageaccount1'
    backendAzureRmContainerName: 'sxpstoragecontainer'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  displayName: 'validate'
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  displayName: 'plan'
  inputs:
    command: 'plan'
    environmentServiceName: 'azure-service-connection'
    commandOptions: '-destroy -out main.destroy.tfplan'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  displayName: 'apply'
  inputs:
    command: 'apply'
    environmentServiceName: 'azure-service-connection'
    commandOptions: 'main.destroy.tfplan'
    allowTelemetryCollection: true